services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: "${UID}"
    ports:
      - 8080:8080
    command: cargo watch -x "run --bin main"
    working_dir: /home/docker/crust
    volumes:
      - ./.env:/home/docker/crust/.env
      - ./Cargo.lock:/home/docker/crust/Cargo.lock
      - ./Cargo.toml:/home/docker/crust/Cargo.toml
      - ./migrations:/home/docker/crust/migrations
      - ./src:/home/docker/crust/src

  postgres:
    image: docker.io/library/postgres:17.0-bookworm@sha256:8d3be35b184e70d81e54cbcbd3df3c0b47f37d06482c0dd1c140db5dbcc6a808
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
